// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIGyKpaMDCTSQJ7cMJj31BYqO_ljtcXY',
    appId: '1:110457770025:web:9138e446aeb047a8290c38',
    messagingSenderId: '110457770025',
    projectId: 'homecook-9e577',
    authDomain: 'homecook-9e577.firebaseapp.com',
    storageBucket: 'homecook-9e577.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UA6EJT8-YedwOhpS0Bo8AqXuQQWA3j0',
    appId: '1:110457770025:android:4778243da249fd3e290c38',
    messagingSenderId: '110457770025',
    projectId: 'homecook-9e577',
    storageBucket: 'homecook-9e577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDErSAgavKwhErCp9ZmpytjaaL41B8wBEQ',
    appId: '1:110457770025:ios:ebe42c8066897d61290c38',
    messagingSenderId: '110457770025',
    projectId: 'homecook-9e577',
    storageBucket: 'homecook-9e577.firebasestorage.app',
    iosBundleId: 'com.example.homecook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDErSAgavKwhErCp9ZmpytjaaL41B8wBEQ',
    appId: '1:110457770025:ios:ebe42c8066897d61290c38',
    messagingSenderId: '110457770025',
    projectId: 'homecook-9e577',
    storageBucket: 'homecook-9e577.firebasestorage.app',
    iosBundleId: 'com.example.homecook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYIGyKpaMDCTSQJ7cMJj31BYqO_ljtcXY',
    appId: '1:110457770025:web:6fb5b35f94302aa1290c38',
    messagingSenderId: '110457770025',
    projectId: 'homecook-9e577',
    authDomain: 'homecook-9e577.firebaseapp.com',
    storageBucket: 'homecook-9e577.firebasestorage.app',
  );

}